/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeApp */

#ifndef _Included_NativeApp
#define _Included_NativeApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeApp
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeApp_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
